version: '3.8'

services:
  tradingklx:
    build: .
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1
    command: bash -c "./build.sh && ./RunTradingKLX.sh"
    extra_hosts:
      - "host.docker.internal:host-gateway"