version: '3.8'

services:
  tradingklx:
    build: .
    ports:
      - "3000:3000"
      - "2222:22"
    environment:
      - PYTHONUNBUFFERED=1
    command: bash -c "./build.sh && ./RunTradingKLX.sh"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
